# FindAble Schema Injection — Theme App Extension
# https://shopify.dev/docs/apps/build/online-store/theme-app-extensions

type = "theme"
name = "FindAble Schema"
uid = "e450fdf5-f7a3-16bb-c094-f5f3b6d10ce3ae32d64b"
